<?php
namespace Headzoo\Nexmo;

use Iterator;
use Countable;

/**
 * Represents a response from the Nexmo API.
 */
class Response
    implements Iterator, Countable
{
    /**
     * @var Message[]
     */
    private $messages = [];
    
    /**
     * @var Exception\Exception[]
     */
    private $exceptions = [];
    
    /**
     * @var int
     */
    private $count = 0;

    /**
     * @var int
     */
    private $position = 0;

    /**
     * Constructor
     * 
     * @param array $messages   Each message sent
     * @param array $exceptions Any exceptions generated by the request
     */
    public function __construct(array $messages, array $exceptions = [])
    {
        $this->count      = count($messages);
        $this->messages   = $messages;
        $this->exceptions = $exceptions;
    }

    /**
     * Returns an array of each message sent
     * 
     * @return Message[]
     */
    public function getMessages()
    {
        return $this->messages;
    }

    /**
     * Returns an array of each exception generated by the request
     * 
     * @return Exception\Exception[]
     */
    public function getExceptions()
    {
        return $this->exceptions;
    }

    /**
     * Returns the number of messages in the response
     *
     * @return int
     */
    public function count()
    {
        return $this->count;
    }

    /**
     * Return the current element
     *
     * @return Message
     */
    public function current()
    {
        return $this->messages[$this->position];
    }

    /**
     * Move forward to next element
     *
     * @return void
     */
    public function next()
    {
        ++$this->position;
    }

    /**
     * Return the key of the current element
     *
     * @return int
     */
    public function key()
    {
        return $this->position;
    }

    /**
     * Checks if current position is valid
     *
     * @return boolean
     */
    public function valid()
    {
        return isset($this->messages[$this->position]);
    }

    /**
     * Rewind the Iterator to the first element
     *
     * @return void
     */
    public function rewind()
    {
        $this->position = 0;
    }
}